### ISSUE TITLE
Would like support reading to Uint8Array in Parser.toObject 

### ISSUE THREAD

**Issue by snosenzo** [jkuszmaul/flatbuffers_reflection#22]
In [adding support for flatbuffers](https://github.com/foxglove/schemas/pull/70) in @foxglove/schemas, I was testing the creation of an mcap file containing a `foxglove.Grid` which includes a Uint8 data array, and found that the renderer was spending a long time normalizing the Grid messages `data` field from `Array` to `Uint8Array` type. 

Would this be hard to add? It would greatly increase the performance for larger data arrays. 

Looks like you have a TODO here for it?
https://github.com/jkuszmaul/flatbuffers_reflection/blob/main/src/reflection.ts#L412

happy to attempt a PR on this too if you don't have time.

**Comment by jkuszmaul** [comment]
It should be reasonably straightforward to add, although I'd need to refresh myself on how exactly studio's parsers manage these things to ensure I actually implemented the correct feature. I'll plan to add it myself sometime soon (should probably also accept some of the version bump PR's for the dependencies....).

**Comment by jkuszmaul** [comment]
Ah, you may want to generate the patch then. I'm at a conference this week and so am not going to be reliable in getting it done this week.

**Comment by snosenzo** [comment]
All good, I think I have a fix, but it looks like I don't have permission to push a branch to make a PR?
I can try patching in the meantime though

**Comment by jtbandes** [comment]
> looks like I don't have permission to push a branch to make a PR?

The normal way of doing this would be to make a fork of the repo

**Comment by jkuszmaul** [comment]
Hopefully solved, thanks @snosenzo
