### ISSUE TITLE
vtable bounds checks shouldn't operate on structs

### ISSUE THREAD

**Issue by jameskuszmaul-brt** [jkuszmaul/flatbuffers_reflection#62]
From the foxglove community slack:
> Sounds like more tests are in order. Fix should be reasonably straightforwards--basically, vtables don't exist for structs, so all of https://github.com/jkuszmaul/flatbuffers_reflection/blob/main/src/reflection.ts#L136-L170 should just not get run if the type is a struct. And readTableLambda  should pass in an isStruct parameter or something to the Table object so it can do/not do the verification. Should be pretty straightforwards to do. Not entirely sure how soon I could get to it, but if someone else does, I'm happy to review & approve.

**Comment by james-rms** [comment]
Foxglove linear: https://linear.app/foxglove/issue/FG-3669/studio-cannot-parse-some-flatbuffer-schemas-relating-to-nested-structs
